name: niri
description: A starting point for Dart libraries or applications.
version: 1.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.9.0
  mutex: ^3.1.0
  # path: ^1.9.0

dev_dependencies:
  build_runner: ^2.10.3
  json_serializable: ^6.11.1
  lints: ^6.0.0
  test: ^1.25.6
